servers:
  custom: bizrag/servers/custom
  dense: bizrag/servers/retriever
  sparse: bizrag/servers/retriever
  reranker: bizrag/servers/reranker
  prompt_builder: bizrag/servers/prompt
  generation: bizrag/servers/generation

pipeline:
- custom.build_classic_read_inputs
- dense.retriever_init
- sparse.retriever_init
- dense.retriever_search_structured:
    input:
      query_list: query_list
      top_k: retrieval_top_k
      query_instruction: query_instruction
      collection_name: $collection_name
      filters: filters
      output_fields: output_fields
    output:
      ret_items: ret_items
- sparse.bm25_search_structured:
    input:
      query_list: query_list
      top_k: retrieval_top_k
      filters: filters
      output_fields: output_fields
    output:
      ret_items: temp_items
- custom.merge_retrieve_items:
    input:
      ret_items: ret_items
      temp_items: temp_items
      top_k: merge_top_k
      strategy: $strategy
      rrf_k: $rrf_k
      primary_weight: $primary_weight
      secondary_weight: $secondary_weight
- reranker.reranker_init
- reranker.reranker_rerank_items:
    input:
      query_list: query_list
      ret_items: ret_items
      top_k: reranker_top_k
      query_instruction: query_instruction
- custom.retrieve_items_to_passages:
    input:
      ret_items: ret_items
- prompt_builder.qa_rag:
    input:
      q_ls: q_ls
      ret_psg: ret_psg
- generation.generation_init
- generation.generate:
    input:
      prompt_ls: prompt_ls
      system_prompt: $system_prompt
