retriever:
  parameter: bizrag/servers/retriever/parameter.yaml
  path: bizrag/servers/retriever/retriever.py
  tools:
    retriever_init:
      input:
        model_name_or_path: $model_name_or_path
        backend_configs: $backend_configs
        batch_size: $batch_size
        corpus_path: $corpus_path
        gpu_ids: $gpu_ids
        is_multimodal: $is_multimodal
        backend: $backend
        index_backend: $index_backend
        index_backend_configs: $index_backend_configs
        is_demo: $is_demo
        collection_name: $collection_name
    retriever_drop_collection:
      input:
        collection_name: $collection_name
