benchmark:
  parameter: bizrag/servers/benchmark/parameter.yaml
  path: bizrag/servers/benchmark/benchmark.py
  tools:
    get_data:
      input:
        benchmark: $benchmark
      output:
      - q_ls
      - gt_ls
dense:
  parameter: bizrag/servers/retriever/parameter.yaml
  path: bizrag/servers/retriever/retriever.py
  tools:
    retriever_init:
      input:
        model_name_or_path: $model_name_or_path
        backend_configs: $backend_configs
        batch_size: $batch_size
        corpus_path: $corpus_path
        gpu_ids: $gpu_ids
        is_multimodal: $is_multimodal
        backend: $backend
        index_backend: $index_backend
        index_backend_configs: $index_backend_configs
        is_demo: $is_demo
        collection_name: $collection_name
    retriever_search_structured:
      input:
        query_list: $query_list
        top_k: $top_k
        query_instruction: $query_instruction
        collection_name: $collection_name
        filters: $filters
        output_fields: $output_fields
      output:
      - ret_items
sparse:
  parameter: bizrag/servers/retriever/parameter.yaml
  path: bizrag/servers/retriever/retriever.py
  tools:
    retriever_init:
      input:
        model_name_or_path: $model_name_or_path
        backend_configs: $backend_configs
        batch_size: $batch_size
        corpus_path: $corpus_path
        gpu_ids: $gpu_ids
        is_multimodal: $is_multimodal
        backend: $backend
        index_backend: $index_backend
        index_backend_configs: $index_backend_configs
        is_demo: $is_demo
        collection_name: $collection_name
    bm25_search_structured:
      input:
        query_list: $query_list
        top_k: $top_k
        filters: $filters
        output_fields: $output_fields
      output:
      - ret_items
reranker:
  parameter: bizrag/servers/reranker/parameter.yaml
  path: bizrag/servers/reranker/reranker.py
  tools:
    reranker_init:
      input:
        model_name_or_path: $model_name_or_path
        backend_configs: $backend_configs
        batch_size: $batch_size
        gpu_ids: $gpu_ids
        backend: $backend
    reranker_rerank_items:
      input:
        query_list: $query_list
        ret_items: ret_items
        top_k: $top_k
        query_instruction: $query_instruction
      output:
      - ret_items
custom:
  parameter: bizrag/servers/custom/parameter.yaml
  path: bizrag/servers/custom/custom.py
  tools:
    merge_retrieve_items:
      input:
        ret_items: ret_items
        temp_items: temp_items
        top_k: $top_k
        strategy: $strategy
        rrf_k: $rrf_k
        primary_weight: $primary_weight
        secondary_weight: $secondary_weight
      output:
      - ret_items
    retrieve_items_to_passages:
      input:
        ret_items: ret_items
      output:
      - ret_psg
    output_extract_from_boxed:
      input:
        ans_ls: ans_ls
      output:
      - pred_ls
prompt_builder:
  parameter: bizrag/servers/prompt/parameter.yaml
  path: bizrag/servers/prompt/prompt.py
  tools:
    qa_rag_boxed:
      input:
        q_ls: $q_ls
        ret_psg: ret_psg
        template: $template
      output:
      - prompt_ls
generation:
  parameter: bizrag/servers/generation/parameter.yaml
  path: bizrag/servers/generation/generation.py
  tools:
    generation_init:
      input:
        backend_configs: $backend_configs
        sampling_params: $sampling_params
        extra_params: $extra_params
        backend: $backend
    generate:
      input:
        prompt_ls: prompt_ls
        system_prompt: $system_prompt
      output:
      - ans_ls
evaluation:
  parameter: bizrag/servers/evaluation/parameter.yaml
  path: bizrag/servers/evaluation/evaluation.py
  tools:
    evaluate:
      input:
        pred_ls: pred_ls
        gt_ls: gt_ls
        metrics: $metrics
        save_path: $save_path
      output:
      - eval_res
