# servers/reranker/parameter.yaml

model_name_or_path: BAAI/bge-reranker-large
backend: sentence_transformers # options: infinity, sentence_transformers, openai
backend_configs:
  infinity:
    bettertransformer: false
    pooling_method: auto
    device: cpu
    model_warmup: false
    trust_remote_code: true
  sentence_transformers:
    device: cpu
    trust_remote_code: true
    local_files_only: true
  openai:
    model_name: text-embedding-3-small
    base_url: "https://api.openai.com/v1"
    api_key: ""

gpu_ids: null
top_k: 5
reranker_top_k: 5
batch_size: 16
query_instruction: ""
query_list: []
ret_items: []
passages_list: []
